### ISSUE TITLE
dataall CDK synth fails on windows

### ISSUE THREAD

**Issue by ahom** [awslabs/aws-dataall#109]
### Describe the bug

Running CDK synth on dataall from a windows shell is failing due to unix commands used in `deploy/stacks/solution_bundling.py` to bundle lambda functions: https://github.com/awslabs/aws-dataall/blob/main/deploy/stacks/solution_bundling.py#L9 

### How to Reproduce

Run CDK synth in windows shell, leading to the following error:

``` 
Bundling asset dataall-main-cicd-stack/dataall-prd-backend-stage/backend-stack/Cognito/CognitoParamsSyncHandlerprd/Code/Stage...
jsii.errors.JavaScriptError:
  Error: Failed to bundle asset dataall-main-cicd-stack/dataall-prd-backend-stage/backend-stack/Cognito/CognitoParamsSyncHandlerprd/Code/Stage, bundle output is located at C:\Users\anhom\projects\aws-dataall\cdk.out\asset.2cd6fafc2341be652b93379d7b28312db9820e80e01c47930667c0815c206979-error: Error: Command '['cp -a C:\\Users\\anhom\\projects\\aws-dataall\\deploy\\custom_resources\\sync_congito_params/. C:\\Users\\anhom\\projects\\aws-dataall\\cdk.out\\asset.2cd6fafc2341be652b93379d7b28312db9820e80e01c47930667c0815c206979/ && pip install -r C:\\Users\\anhom\\projects\\aws-dataall\\deploy\\custom_resources\\sync_congito_params\\requirements.txt -t C:\\Users\\anhom\\projects\\aws-dataall\\cdk.out\\asset.2cd6fafc2341be652b93379d7b28312db9820e80e01c47930667c0815c206979']' returned non-zero exit status 1.
      at AssetStaging.bundle (C:\Users\anhom\AppData\Local\Temp\jsii-kernel-4xytib\node_modules\aws-cdk-lib\core\lib\asset-staging.js:2:672)
      at AssetStaging.stageByBundling (C:\Users\anhom\AppData\Local\Temp\jsii-kernel-4xytib\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:4168)
      at stageThisAsset (C:\Users\anhom\AppData\Local\Temp\jsii-kernel-4xytib\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:1675)
      at Cache.obtain (C:\Users\anhom\AppData\Local\Temp\jsii-kernel-4xytib\node_modules\aws-cdk-lib\core\lib\private\cache.js:1:242)
      at new AssetStaging (C:\Users\anhom\AppData\Local\Temp\jsii-kernel-4xytib\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:2070)
      at new Asset (C:\Users\anhom\AppData\Local\Temp\jsii-kernel-4xytib\node_modules\aws-cdk-lib\aws-s3-assets\lib\asset.js:1:620)
      at AssetCode.bind (C:\Users\anhom\AppData\Local\Temp\jsii-kernel-4xytib\node_modules\aws-cdk-lib\aws-lambda\lib\code.js:1:3506)
      at new Function (C:\Users\anhom\AppData\Local\Temp\jsii-kernel-4xytib\node_modules\aws-cdk-lib\aws-lambda\lib\function.js:1:2424)
      at Kernel._create (C:\Users\anhom\AppData\Local\Temp\tmpn1rqmgdq\lib\program.js:8223:29)
      at Kernel.create (C:\Users\anhom\AppData\Local\Temp\tmpn1rqmgdq\lib\program.js:7961:29)
```

### Expected behavior

CDK synth completes successfully.

### OS

Win

### Python version

3.9

### AWS data.all version

https://github.com/awslabs/aws-dataall/commit/1c0f4f253c536e88d22ca2cd6fa8e0059774dc8b

### Additional context

The two lambdas that are using the class `SolutionBundling` actually do not need it:
* [docs_http_headers](https://github.com/awslabs/aws-dataall/tree/main/deploy/custom_resources/docs_http_headers) is a javascript function with no dependencies
* [sync_cognito_params](https://github.com/awslabs/aws-dataall/tree/main/deploy/custom_resources/sync_congito_params) do not have any dependencies

I would suggest to remove this custom bundling as it is unnecessary and leads to the inability to build aws-dataall CDK app on windows shell.
*If this is the solution that you would recommend I can create a pull request as I already did this fix on my end.*
#112

**Comment by dlpzx** [comment]
Instead of building an alternative for Windows, we would propose to use the linux subsystem for windows, or just spin up a remote instance and use it.
