### ISSUE TITLE
JSII Error with "enable_cw_rum" set to true

### ISSUE THREAD

**Issue by mgwidmann** [awslabs/aws-dataall#216]
### Describe the bug

Running `cdk synth` produces a python crash for a JSII related error.

```
(venv) ➜  aws-dataall git:(main) ✗ cdk synth
[2022-11-18 11:30:55,095][app.py       : 40] Trying to get cdkjson parameter from SSM
[2022-11-18 11:30:55,211][app.py       : 49] SSM parameter not found - Proceeding with cdk.json and cdk.context.json in code
[2022-11-18 11:30:55,216][app.py       : 54] Loaded context from cdk.json file in repository
Traceback (most recent call last):
  File "./deploy/app.py", line 68, in <module>
    pipeline = PipelineStack(
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_runtime.py", line 109, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/matt/projects/aws-dataall/deploy/stacks/pipeline.py", line 295, in __init__
    self.set_albfront_stage(target_env, repository_name)
  File "/Users/matt/projects/aws-dataall/deploy/stacks/pipeline.py", line 737, in set_albfront_stage
    albfront_stage = self.pipeline.add_stage(
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/aws_cdk/pipelines/__init__.py", line 3306, in add_stage
    return typing.cast("StageDeployment", jsii.invoke(self, "addStage", [stage, options]))
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 148, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 390, in invoke
    args=_make_reference_for_native(self, args),
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 164, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 164, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 181, in _make_reference_for_native
    "data": {
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 182, in <dictcomp>
    jsii_name: _make_reference_for_native(
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 204, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "/Users/matt/projects/aws-dataall/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 323, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'tuple' has no attribute '__jsii_type__'

NOTICES

19179	(aws-eks): Regression in installing Helm charts from assets

	Overview: Helm charts fail to install when provided as an asset. This
	          issue does not affect charts installed from a repository.

	Affected versions: framework: 2.14.0, framework: 1.146.0

	More information at: https://github.com/aws/aws-cdk/issues/19179


If you don’t want to see a notice anymore, use "cdk acknowledge <id>". For example, "cdk acknowledge 19179".
Subprocess exited with error 1
```

### How to Reproduce

Using the following `cdk.json`:

```json
{
  "app": "python ./deploy/app.py",
  "context": {
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": false,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": false,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": false,
    "@aws-cdk/core:stackRelativeExports": false,
    "DeploymentEnvironments": [
      {
        "envname": "dev",
        "account": "123456789012",
        "region": "us-west-1",
        "internet_facing": false,
        "custom_domain": {
          "hosted_zone_name": "mysite.example.com",
          "hosted_zone_id": "ABCDEFGHIJLMNOPQRSTUV",
          "certificate_arn": "arn:aws:acm:us-east-1:123456789012:certificate/abcdef01-2345-6789-0abc-def012345678"
        },
        "ip_ranges": ["172.121.96.167/32"],
        "enable_cw_rum": true,
        "enable_cw_canaries": true
      }
    ]
  }
}
```

These are obviously faked values, but it does the same with my real values. Something is wrong with the configuration and I'm not sure what it is at this time.

### Expected behavior

The error or misconfiguration is reported to the console or the synthesis succeeds.

### OS

Mac

### Python version

3.8.15

### AWS data.all version

0.5.0

### Additional context

Trying to deploy data.all for the first time, so I probably have something messed up in the configuration somewhere but since the error reported is not relevant, I'm unsure where to start debugging this.

**Comment by mgwidmann** [comment]
I've found that the `"enable_cw_rum": true,` is the offending part of the configuration. It seems through some debugging on my own that there is a python bug in the data.all code. Through printing some of the internal objects, I am able to see that the `post` field of `AddStageOpts` is a 1-tuple containing a list of 2 elements when it looks like it should probably be a list only.

```
<stacks.albfront_stage.AlbFrontStage object at 0x121124a30> AddStageOpts(post=([<aws_cdk.pipelines.CodeBuildStep object at 0x12150e2e0>, <aws_cdk.pipelines.CodeBuildStep object at 0x1215f2b80>],), ...
```

The bug is a trailing comma right here:
https://github.com/awslabs/aws-dataall/blob/main/deploy/stacks/pipeline.py#L830

Looks like its been there for 8 months. Should probably add a unit test to synthesize with this configuration.

**Comment by dlpzx** [comment]
I am going to try with `enable_cw_rum` enabled and follow your recommendation for the bug. Otherwise you are more than welcome to open a PR with the fix :)

**Comment by dlpzx** [comment]
Hi @mgwidmann, I have tried with this `cdk.json` and it works fine (I am using Python 3.9):
```{
  "app": "python ./deploy/app.py",
  "context": {
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": false,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": false,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": false,
    "@aws-cdk/core:stackRelativeExports": false,
    "tooling_region": "eu-west-1",
    "git_branch": "v1m4m0",
    "resource_prefix": "version",
    "DeploymentEnvironments": [
      {
        "envname": "version",
        "account": "AWS_ACCOUNT",
        "region": "eu-west-1",
        "prod_sizing": false,
        "enable_cw_rum":  true,
        "enable_cw_canaries": true
      }
    ]
  }
}
```
I also tested the other piece (custom domain) recently, so I am struggling to see where your issue might come from. I noted that I am using Python 3.9 just in case it has to do with the Python version.
I'll keep on debugging and I will let you know if I can recreate the issue, otherwise please feel free to share your findings here :)

**Comment by mgwidmann** [comment]
I'm a bit confused why you're not seeing the error. Perhaps CDK/JSII version differences or Python 3.9 being more forgiving for trailing commas (I doubt this) but as I pointed out before [this line](https://github.com/awslabs/aws-dataall/blob/main/deploy/stacks/pipeline.py?rgh-link-date=2022-11-18T17%3A44%3A57Z#L830) has a trailing comma which causes Python to interpret that as a tuple element. It seems in my version, JSII is unable to translate that to a type on the javascript side.

Its clearly a bug in the code. I'm not sure why you're not experiencing it, but if you look at the code its clearly wrong.

**Comment by dlpzx** [comment]
I agree with you. Even if it works the code is wrongly written. Let's fix this. Thank you for the contribution
