### ISSUE TITLE
node version upgrade needed

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#38]
### Describe the bug

Node version 12 on CodeBuild results in :

""""
[Container] 2022/06/09 10:03:38 Running command cdk synth

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                            !!
!!  Node 12 has reached end-of-life on 2022-04-30 and is not supported.       !!
!!  Please upgrade to a supported node version as soon as possible.           !!
!!                                                                            !!
!!  This software is currently running on node v12.22.2.                      !!
!!  As of the current release of this software, supported node releases are:  !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                               !!
!!  - ^16.3.0 (Planned end-of-life: 2024-04-30)                               !!
!!  - ^14.5.0 (Planned end-of-life: 2023-04-30)                               !!
!!                                                                            !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

b'/tmp/tmp_suwj4k7/bin/jsii-runtime.js:3666\n'

b'                this.untested = opts.untested ?? false;\n'

b'                                               ^\n'

b'\n'

b"SyntaxError: Unexpected token '?'\n"

b'    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n'

b'    at Module._compile (internal/modules/cjs/loader.js:963:27)\n'

b'    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n'

b'    at Module.load (internal/modules/cjs/loader.js:863:32)\n'

b'    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n'

b'    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)\n'

b'    at internal/main/run_main_module.js:17:47\n'

Traceback (most recent call last):

  File "/codebuild/output/src440001176/src/./deploy/app.py", line 7, in <module>

    from aws_cdk import App, Environment, Aspects

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/__init__.py", line 1051, in <module>

    from ._jsii import *

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/aws_cdk/_jsii/__init__.py", line 11, in <module>

    import constructs._jsii

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/constructs/__init__.py", line 41, in <module>

    from ._jsii import *

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/constructs/_jsii/__init__.py", line 11, in <module>

    __jsii_assembly__ = jsii.JSIIAssembly.load(

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_runtime.py", line 43, in load

    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 269, in load

    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 338, in load

    return self._process.send(request, LoadResponse)

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_utils.py", line 24, in wrapped

    stored.append(fgetter(self))

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 333, in _process

    process.start()

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 275, in start

    self.handshake()

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 299, in handshake

    self._next_message(), _HelloResponse

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 242, in _next_message

    return json.loads(self._process.stdout.readline(), object_hook=ohook)

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/json/__init__.py", line 359, in loads

    return cls(**kw).decode(s)

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Error in atexit._run_exitfuncs:

Traceback (most recent call last):

  File "/root/.pyenv/versions/3.9.5/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 284, in stop

    self._process.stdin.close()

BrokenPipeError: [Errno 32] Broken pipe

Subprocess exited with error 1
""""

### How to Reproduce

```
By running the deployment CodePipeline, even without any code changes this bug will appear
```

### OS

Linux

### Python version

3.9

### AWS data.all version

1.0

**Comment by dlpzx** [comment]
PR completed in hotfixes branch
