### ISSUE TITLE
cdk deploy execution error

### ISSUE THREAD

**Issue by miteshdesai1989** [awslabs/aws-dataall#496]
### Describe the bug

Hello,

We are trying to deploy the data.all environment for a customer, where we are trying to have both tooling and deployment resources in the same account/region. When doing `cdk deploy`, we are getting below error:
```
❌  cross-region-stack-922835841938:us-east-1 (dataall-main-cicd-stack-support-us-east-1) failed: Error [ValidationError]: Role arn:aws:iam::922835841938:role/cdk-dataall-cfn-exec-role-922835841938-eu-west-1 is invalid or cannot be assumed
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:46245)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:89237)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:88685)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:195114)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:188666)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:153538)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:292:153868
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:188958)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:195189)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:89405) {
  code: 'ValidationError',
  time: 2023-06-06T08:20:46.508Z,
  requestId: '1f6651f0-5d75-4b16-a6db-2b700ed6f169',
  statusCode: 400,
  retryable: false,
  retryDelay: 61.24542901195262
}

 ❌ Deployment failed: Error [ValidationError]: Role arn:aws:iam::922835841938:role/cdk-dataall-cfn-exec-role-922835841938-eu-west-1 is invalid or cannot be assumed
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:46245)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:89237)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:88685)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:195114)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:188666)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:153538)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:292:153868
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:188958)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:195189)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:292:89405) {
  code: 'ValidationError',
  time: 2023-06-06T08:20:46.508Z,
  requestId: '1f6651f0-5d75-4b16-a6db-2b700ed6f169',
  statusCode: 400,
  retryable: false,
  retryDelay: 61.24542901195262
}

Role arn:aws:iam::922835841938:role/cdk-dataall-cfn-exec-role-922835841938-eu-west-1 is invalid or cannot be assumed
```
We are using below package versions:
```
aws-cdk-lib==2.77.0
boto3-stubs==1.20.20
boto3==1.24.85
botocore==1.27.85
cdk-nag==2.7.2
constructs>=10.0.0,<11.0.0
```

### How to Reproduce

```
cdk deploy <resource_name>
```

### Expected behavior

The stacks and resources should be created

### OS

Mac

### Python version

3.8

### AWS data.all version

latest

**Comment by dlpzx** [comment]
Hi @miteshdesai1989 just to make sure that your problem was solved, was it related to bootstraping in the replication region?

**Comment by gmuslia** [comment]
@dlpzx the issue was related to not passing the --qualifier dataall in the cli during bootstrap as we have a custom cdk bootstrap qualifier defined in the cdk.json and the roles created during bootstrap werent matching with the ones cdk deploy was trying to use.
