### ISSUE TITLE
Profille Job run fails

### ISSUE THREAD

**Issue by marjet26** [awslabs/aws-dataall#533]
### Describe the bug

The profile Job execution fails with error: 
sqlalchemy.exc.DataError: (pg.DataError) ERROR:  invalid input syntax for type json

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

Run Profile job run

### Screenshots

[ERROR]	2023-06-26T07:54:18.729Z	1fee6ae5-35bd-5443-b29b-37f673e4448c	Error in process
--
Traceback (most recent call last):
File "/home/app/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/home/app/sqlalchemy/engine/default.py", line 608, in do_execute
cursor.execute(statement, parameters)
File "/home/app/pgdb.py", line 1110, in execute
return self.executemany(operation, [parameters])
File "/home/app/pgdb.py", line 1135, in executemany
rows = self._src.execute(sql)
pg.DataError: ERROR:  invalid input syntax for type json
LINE 1: ...'2023-06-26 07:50:25.428721'::timestamp, response='FAILED', ...
^
DETAIL:  Token "FAILED" is invalid.
CONTEXT:  JSON data, line 1: FAILED
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/app/dataall/aws/handlers/service_handlers.py", line 46, in process
WorkerHandler.update_task(
File "/home/app/dataall/aws/handlers/service_handlers.py", line 106, in update_task
session.commit()
File "/home/app/sqlalchemy/orm/session.py", line 1046, in commit
self.transaction.commit()
File "/home/app/sqlalchemy/orm/session.py", line 504, in commit
self._prepare_impl()
File "/home/app/sqlalchemy/orm/session.py", line 483, in _prepare_impl
self.session.flush()
File "/home/app/sqlalchemy/orm/session.py", line 2540, in flush
self._flush(objects)
File "/home/app/sqlalchemy/orm/session.py", line 2682, in _flush
transaction.rollback(_capture_exception=True)
File "/home/app/sqlalchemy/util/langhelpers.py", line 68, in __exit__
compat.raise_(
File "/home/app/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/home/app/sqlalchemy/orm/session.py", line 2642, in _flush
flush_context.execute()
File "/home/app/sqlalchemy/orm/unitofwork.py", line 422, in execute
rec.execute(self)
File "/home/app/sqlalchemy/orm/unitofwork.py", line 586, in execute
persistence.save_obj(
File "/home/app/sqlalchemy/orm/persistence.py", line 230, in save_obj
_emit_update_statements(
File "/home/app/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
c = cached_connections[connection].execute(
File "/home/app/sqlalchemy/engine/base.py", line 1011, in execute
return meth(self, multiparams, params)
File "/home/app/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/home/app/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
ret = self._execute_context(
File "/home/app/sqlalchemy/engine/base.py", line 1316, in _execute_context
self._handle_dbapi_exception(
File "/home/app/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
util.raise_(
File "/home/app/sqlalchemy/util/compat.py", line 182, in raise_
raise exception

### OS

linux

### Python version

3.7+

### AWS data.all version

1.5.4

**Comment by dlpzx** [comment]
Thanks for opening the issue, we are working on it for v1.6 in #506

**Comment by dlpzx** [comment]
I verified that this issue has been fixed in V2. Closing as resolved.
