### ISSUE TITLE
cognito_urls_config: InvalidPasswordException

### ISSUE THREAD

**Issue by InasK6** [awslabs/aws-dataall#690]
**Is your idea related to a problem?** 
The code snippet in function **setup_cognito** in **deploy/configs/cognito_urls_config** line 117 to 123 doesn't guarantee that in the 13 characters generated, there will be at least one Uppercase character and at least one digit. 
The following screenshot shows an issue encountered where all 13 characters generated were only Uppercase characters, with 0 digits.

```
Creating Canaries user...
--
119 | Failed to setup cognito due to: An error occurred (InvalidPasswordException) when calling the AdminCreateUser operation: Password did not conform with password policy: Password must have numeric characters
120 | Traceback (most recent call last):
121 | File "/codebuild/output/src1068045984/src/deploy/configs/cognito_urls_config.py", line 172, in <module>
122 | setup_cognito(
123 | File "/codebuild/output/src1068045984/src/deploy/configs/cognito_urls_config.py", line 161, in setup_cognito
124 | raise e
125 | File "/codebuild/output/src1068045984/src/deploy/configs/cognito_urls_config.py", line 131, in setup_cognito
126 | raise e
127 | File "/codebuild/output/src1068045984/src/deploy/configs/cognito_urls_config.py", line 111, in setup_cognito
128 | response = cognito.admin_create_user(
129 | File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/botocore/client.py", line 391, in _api_call
130 | return self._make_api_call(operation_name, kwargs)
131 | File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/botocore/client.py", line 719, in _make_api_call
132 | raise error_class(parsed_response, operation_name)
133 | botocore.errorfactory.InvalidPasswordException: An error occurred (InvalidPasswordException) when calling the AdminCreateUser operation: Password did not conform with password policy: Password must have numeric characters
134 |  
135 | [Container] 2023/08/22 15:32:19 Command did not exit successfully if [[ -n "$domain" ]]; then echo "cloudfront already created"; python deploy/configs/cognito_urls_config.py; fi exit status 1
136 | [Container] 2023/08/22 15:32:19 Phase complete: BUILD State: FAILED
137 | [Container] 2023/08/22 15:32:19 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [[ -n "$domain" ]]; then echo "cloudfront already created"; python deploy/configs/cognito_urls_config.py; fi. Reason: exit status 1
138 | [Container] 2023/08/22 15:32:19 Entering phase POST_BUILD
139 | [Container] 2023/08/22 15:32:19 Phase complete: POST_BUILD State: SUCCEEDED
140 | [Container] 2023/08/22 15:32:19 Phase context status code:  Message:


```

![Capture d’écran 2023-08-22 à 17 52 01](https://github.com/awslabs/aws-dataall/assets/47898937/e80a8e07-cd85-4692-b5a0-dfc2b4b5adb8)

**Describe the solution you'd like**
To solve the issue and ensure the password meets the conditions required by cognito(at least 1 digit, at least 1 uppercase character, at least 1 lowercase character, at least 1 special character)
we can either modify the prefix to make it meet those requirements from :
`TemporaryPassword='da@'`
to 
`TemporaryPassword='da@1A'`

or change the code as follows: 
```
random_part = ''.join(
    random.SystemRandom().choice(
        string.ascii_uppercase + string.digits
    )
    for _ in range(13)
)

# Ensure there's at least one digit and one uppercase letter
if not any(char.isdigit() for char in random_part):
    random_part = random_part[:-1] + random.choice(string.digits)

if not any(char.isupper() for char in random_part):
    random_part = random_part[:-1] + random.choice(string.ascii_uppercase)
response = cognito.admin_create_user(
                    UserPoolId=user_pool_id,
                    Username=username,
                    UserAttributes=[
                        {'Name': 'email', 'Value': f'{username}@amazonaws.com'}
                    ],
                    TemporaryPassword='da@'+ random_part,
                    MessageAction='SUPPRESS',
                )
```

**Comment by dlpzx** [comment]
Good catch @InasK6, thanks for opening an issue and describing the root cause of the bug. Do you want to contribute a fix or should we work on it?

**Comment by InasK6** [comment]
hello @dlpzx , I can contribute. which of the two proposed solutions do you prefer ?

**Comment by InasK6** [comment]
hello, that's correct @noah-paige the modifications in the PR meet the solution needed for this issue
